---
- hosts: new-aws-virginia
  remote_user: '{admin_user}'
  become: yes
  gather_facts: no

  tasks:
   - name: apt-get update
     remote_user: ubuntu
     become: yes
     raw: apt-get update -qq 
   - name: Install python 2.7
     remote_user: ubuntu
     become: yes 
     raw: apt-get install -qq python2.7 
   - name: add {{admin_user}}
     remote_user: ubuntu
     become: yes
     user: name={{admin_user}}
           state=present
           shell=/bin/bash
           groups=root,admin
           home=/home/{{admin_user}}/
   - name: add NOPASSWD for admin group
     remote_user: ubuntu
     become: yes
     lineinfile: dest=/etc/sudoers
                 state=present regexp='^%ADMIN ALL\='
                 line='%ADMIN ALL=(ALL) NOPASSWD:ALL'
   - name: add {{deploy_user}}
     user: name={{deploy_user}}
           state=present
           shell=/bin/bash
           home=/home/{{deploy_user}}/
   - name: Write Authorized key to {{admin_user}}
     authorized_key: user={{admin_user}}
                     key=https://github.com/MikKoz.keys
                     state=present
   - name: Write Authorized key to {{deploy_user}}
     authorized_key: user={{deploy_user}}
                     key={{item}}
                     state=present
     with_items:
      - https://github.com/trrbl.keys
      - https://github.com/MikKoz.keys

   - name: restart machine
     shell: sleep 2 && shutdown -r now "Ansible updates triggered"
     async: 1
     poll: 0
     sudo: true
     ignore_errors: true

   - name: waiting for server to come back
     local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=180
     sudo: false

  vars:
    admin_user: heros-ingeneros
    deploy_user: ruby
    